### ISSUE TITLE
why all packages deprecated when i use npm install

### ISSUE THREAD

**Issue by bahr233** [syncfusion/ej2-showcase-angular-appointment-planner#9]
why all packages deprecated when i use npm install
![1](https://user-images.githubusercontent.com/90806559/171466366-036e8573-84d3-4c5e-80e6-86af8531bd4b.png)

**Comment by ravikumar-venkatesan-m** [comment]
Hi @bahr233 ,
 
We have validated your query “**why all packages deprecated when I use npm install**” at our end. Due to the older version of the angular in the appointment planner, you got the problem. Now we have upgraded the angular appointment planner to angular 13 and resolved the problem that you reported.
 
Kindly let us know if you need any further assistance.
 
Regards,
Ravikumar Venkatesan
